version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
        prefix: "chore: "
    groups:
      experimental-golang-deps:
        patterns:
          - "golang.org/x/*"
      testing-deps:
        patterns:
          - "github.com/onsi/ginkgo/v2"
          - "github.com/onsi/gomega"
      charmbracelet-deps:
          patterns:
              - "github.com/charmbracelet/*"
      koanf-deps:
          patterns:
              - "github.com/knadh/koanf/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore: "
